name: PR
on: [pull_request, workflow_dispatch]
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  trunk_check:
    name: Trunk check runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1

  detect_changes:
    name: Detect changed files
    runs-on: ubuntu-latest

    outputs:
      a: ${{ steps.filter.outputs.a }}
      b: ${{ steps.filter.outputs.b }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Detect changed paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            a: ["a/**"]
            b: ["b/**"]

  test_a:
    name: Test 'a'
    runs-on: ubuntu-latest
    needs: detect_changes
    if: needs.detect_changes.outputs.a == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Test 'a'
        run: echo "Testing a... Done!"

  test_b:
    name: Test 'b'
    runs-on: ubuntu-latest
    needs: detect_changes
    if: needs.detect_changes.outputs.b == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Test 'a'
        run: echo "Testing b... Done!"
